import type { Invoice } from './billing.ts';
const escape=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function aud(value:string):string { const n=BigInt(value),abs=n<0n?-n:n; return `${n<0n?'-':''}A$${abs/100n}.${String(abs%100n).padStart(2,'0')}`; }
function rateAud(value:string):string { const n=BigInt(value); return `A$${n/1_000_000_000n}.${String(n%1_000_000_000n).padStart(9,'0').replace(/0+$/,'')||'00'}`; }
export function invoiceHtml(invoice:Invoice):string {
  const collected=invoice.mode==='commercial' && !!invoice.commercialTerms;
  const abn=invoice.supplier.abn.replace(/^(\d{2})(\d{3})(\d{3})(\d{3})$/,'$1 $2 $3 $4');
  return `<!doctype html><html lang="en-AU"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(invoice.id)} — ${escape(invoice.kind)}</title>
<style>body{font:16px/1.6 system-ui,sans-serif;color:#152e31;max-width:880px;margin:40px auto;padding:0 24px}header{border-bottom:3px solid #267166;padding-bottom:24px}h1{font-size:32px;margin:8px 0}.label{color:#8a4524;font-weight:700}table{width:100%;border-collapse:collapse;margin:32px 0}th,td{text-align:left;border-bottom:1px solid #ddd;padding:12px 8px;vertical-align:top}th:last-child,td:last-child{text-align:right;white-space:nowrap}small{display:block;font-size:12px;overflow-wrap:anywhere}.total{text-align:right;font-size:22px;font-weight:650}@media print{body{margin:0;max-width:none}tr{break-inside:avoid}}</style>
<header>${collected?'':`<div class="label">LOCAL TEST DOCUMENT — no payment requested</div>`}<h1>${escape(invoice.kind)}</h1><b>${escape(invoice.supplier.legalName)}</b> · ABN ${escape(abn)}<br>${invoice.supplier.address?`${escape(invoice.supplier.address)}<br>`:''}RealBud · GST registered</header>
<p><b>${escape(invoice.id)}</b><br>Issued ${escape(new Date(invoice.issuedAt+36_000_000).toISOString().slice(0,10))} (Brisbane) · Billing month ${escape(invoice.period)}</p>
<p><b>Bill to ${escape(invoice.customer.name)}</b><br>${escape(invoice.customer.address)}${invoice.customer.abn?`<br>ABN ${escape(invoice.customer.abn)}`:''}</p>
<table><thead><tr><th>Item and usage</th><th>GST inclusive amount</th></tr></thead><tbody>${invoice.lines.map(l=>`<tr><td>${escape(l.description)}${l.units?`<small>Rate version ${escape(l.rateVersion)} · ${escape(Object.entries(l.units).map(([u,n])=>`${n} ${u.replaceAll('_',' ')}`).join(' · '))}</small><small>${escape(Object.entries(l.rates??{}).map(([u,r])=>`${u.replaceAll('_',' ')}: ${rateAud(r!.nanoAud)} per ${r!.perUnits} units, including GST`).join('; '))}</small>`:''}${l.requestId?`<small>Usage reference ${escape(l.requestId)}</small>`:''}${l.sourceInvoice?`<small>Credit against ${escape(l.sourceInvoice)}</small>`:''}</td><td>${aud(l.amountCents)}</td></tr>`).join('')}</tbody></table>
<p class="total">Total ${aud(invoice.totalCents)}</p><p style="text-align:right">Includes GST ${aud(invoice.gstCents)}</p>
<p><small>Rates are customer retail rates in AUD including GST. Usage is measured by the provider; credits and monthly rounding appear separately. The care fee covers software and routine maintenance. ${collected?`Accepted terms ${escape(invoice.commercialTerms!.version)} · ${escape(invoice.commercialTerms!.digest)}. Payment status and receipts are available in your RealBud account; this invoice alone is not a payment receipt.`:'This local document is for review and does not establish a payment.'}</small></p></html>`;
}
