import { join } from "node:path";

import type { DeskSnapshot } from "../shared/contracts.ts";
import { morningBrief } from "../src/lib/morning-brief.ts";
import { writeFileAtomic } from "./atomic.ts";
import { seedVault } from "./vault.ts";

export const DESK_CONTEXT_FILE = "DESK-CONTEXT.md";

function cell(value: unknown): string {
  return String(value ?? "")
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "\\|")
    .trim();
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

/**
 * A least-privilege projection for Bud's tools. It contains operational
 * facts already visible on Desk, but never contacts, credentials, draft
 * bodies, recovery material, or encrypted storage internals.
 */
export function deskContextMarkdown(snapshot: DeskSnapshot, generatedAt = Date.now()): string {
  const brief = morningBrief(snapshot);
  const attention = new Map(brief.addresses.map((row) => [row.propertyId, row.label]));
  const ledger = new Map(snapshot.ledger.map((row) => [row.propertyId, row]));
  const mode = snapshot.demo || snapshot.mode === "demo" ? "TRAINING SAMPLE" : "OFFICE BOOK";
  const lines = [
    "# Current Desk context",
    "",
    "> Read-only projection generated by RealBud. Use it for current Desk facts.",
    "> Do not inspect desk.json, desk.key, backups, or recovery files. Ask the user to use Desk when more detail is needed.",
    "",
    `- Scope: **${mode}**`,
    `- Jurisdictions: ${snapshot.book?.agency?.jurisdictions?.length ? snapshot.book.agency.jurisdictions.join(", ") : "not named"}`,
    `- Revision: ${snapshot.revision}`,
    `- Generated: ${new Date(generatedAt).toISOString()}`,
    `- Last check: ${snapshot.lastRunAt ? new Date(snapshot.lastRunAt).toISOString() : "not run"}`,
    `- Summary: ${cell(brief.headline)}`,
    "",
    "## Properties",
    "",
    "| Property id | Address | Desk state | Days since due | Rent landed | Levy paid | Days since courtesy | Weekly rent (AUD) |",
    "| --- | --- | --- | ---: | --- | --- | ---: | ---: |",
  ];

  for (const property of snapshot.properties) {
    const facts = ledger.get(property.id);
    lines.push(
      `| ${cell(property.id)} | ${cell(property.address)} | ${cell(attention.get(property.id) ?? "Not checked")} | ${facts?.daysSinceDue ?? "unknown"} | ${facts ? yesNo(facts.rentLanded) : "unknown"} | ${facts ? yesNo(facts.levyPaid) : "unknown"} | ${facts?.daysSinceCourtesy ?? "none"} | ${(property.weeklyRentCents / 100).toFixed(2)} |`,
    );
  }
  if (!snapshot.properties.length) lines.push("| none | No properties on Desk | Not checked | unknown | unknown | unknown | none | unknown |");

  lines.push("", "## Work waiting on Desk", "");
  const pendingDrafts = snapshot.drafts.filter((draft) => draft.status === "pending");
  const rows = [
    ...pendingDrafts.map((draft) => `- Prepared ${cell(draft.kind)} for ${cell(draft.propertyId)}; waiting for a person.`),
    ...snapshot.escalations.map((row) => `- ${cell(row.propertyId)} needs licensed review (${cell(row.reason)}).`),
  ];
  lines.push(...(rows.length ? rows : ["- Nothing is waiting."]));

  lines.push("", "## Source boundary", "");
  lines.push(`- Worker result: ${cell(snapshot.hands)}.`);
  lines.push("- Inbox: not connected.");
  lines.push("- This projection never authorizes sending, paying, submitting, publishing, or issuing a notice.", "");
  return lines.join("\n");
}

export function writeDeskContext(snapshot: DeskSnapshot, book?: string): string {
  const path = join(seedVault(book), DESK_CONTEXT_FILE);
  writeFileAtomic(path, deskContextMarkdown(snapshot), 0o600);
  return path;
}
