import { join } from "node:path";

import type { DeskSnapshot } from "../shared/contracts.ts";
import { morningBrief } from "../src/lib/morning-brief.ts";
import { writeFileAtomic } from "./atomic.ts";
import { seedVault } from "./vault.ts";
import { rentWorkflowContext } from "../shared/rent-workflow.ts";

export const DESK_CONTEXT_FILE = "DESK-CONTEXT.md";
export const DESK_CONTEXT_MAX_CHARS = 64_000;
const MAX_SECTION_ROWS = 500;
const FINISHED_STATES = new Set(["confirmed", "denied", "superseded", "cancelled"]);

function cell(value: unknown): string {
  const text = String(value ?? "")
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "\\|")
    .trim();
  return text.length > 160 ? `${text.slice(0, 157)}...` : text;
}

function boundedRows(rows: Iterable<string>, total: number, budget: number): string[] {
  const shown: string[] = [];
  let length = 0;
  for (const row of rows) {
    if (shown.length >= MAX_SECTION_ROWS || length + row.length + 1 > budget) break;
    shown.push(row);
    length += row.length + 1;
  }
  if (shown.length < total) shown.push(`- Projection incomplete: ${total - shown.length} more records are not included. Narrow the property scope in Desk before preparing work for omitted records.`);
  return shown;
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

/**
 * A least-privilege projection for Bud's tools. It contains operational
 * facts already visible on Desk, but never contacts, credentials, draft
 * bodies, recovery material, or encrypted storage internals.
 */
export function deskContextMarkdown(snapshot: DeskSnapshot, generatedAt = Date.now()): string {
  const brief = morningBrief(snapshot);
  const attention = new Map(brief.addresses.map((row) => [row.propertyId, row.label]));
  const ledger = new Map(snapshot.ledger.map((row) => [row.propertyId, row]));
  const propertyIds = new Set(snapshot.properties.map((property) => property.id));
  const mode = snapshot.demo || snapshot.mode === "demo" ? "TRAINING SAMPLE" : "OFFICE BOOK";
  const lines = [
    "# Current Desk context",
    "",
    "> Read-only snapshot generated by RealBud from saved Desk facts. Generation time does not mean the source was refreshed.",
    "> Do not inspect desk.json, desk.key, backups, or recovery files. Ask the user to use Desk when more detail is needed.",
    "",
    `- Scope: **${mode}**`,
    `- Jurisdictions: ${cell(snapshot.book?.agency?.jurisdictions?.length ? snapshot.book.agency.jurisdictions.join(", ") : "not named")}`,
    `- Book stamp: ${snapshot.revision}`,
    `- Generated: ${new Date(generatedAt).toISOString()}`,
    `- Last check: ${snapshot.lastRunAt ? new Date(snapshot.lastRunAt).toISOString() : "not run"}`,
    `- Money-check summary: ${cell(brief.headline)}`,
    "",
    ...rentWorkflowContext(snapshot.book?.office?.rentWorkflow),
    "## Properties",
    "",
    "| Property id | Address | Desk state | Days since due | Rent landed | Levy paid | Days since courtesy | Weekly rent (AUD) |",
    "| --- | --- | --- | ---: | --- | --- | ---: | ---: |",
  ];

  function* propertyRows() {
    for (const property of snapshot.properties) {
      const facts = ledger.get(property.id);
      yield `| ${cell(property.id)} | ${cell(property.address)} | ${cell(attention.get(property.id) ?? "Not checked")} | ${facts?.daysSinceDue ?? "unknown"} | ${facts ? yesNo(facts.rentLanded) : "unknown"} | ${facts ? yesNo(facts.levyPaid) : "unknown"} | ${facts?.daysSinceCourtesy ?? "none"} | ${(property.weeklyRentCents / 100).toFixed(2)} |`;
    }
  }
  lines.push(...boundedRows(propertyRows(), snapshot.properties.length, 32_000));
  if (!snapshot.properties.length) lines.push("| none | No properties on Desk | Not checked | unknown | unknown | unknown | none | unknown |");

  lines.push("", "## Work waiting on Desk", "");
  // Modern cases are authoritative when a migrated legacy item has the same
  // ID. Scope against the supplied properties: batches pass a one-property
  // snapshot while its book view may still contain the rest of the office.
  const cases = (snapshot.book?.cases ?? []).filter((row) => row.propertyId && propertyIds.has(row.propertyId));
  const caseIds = new Set(cases.map((row) => row.id));
  const work = snapshot.workItems.filter((row) => propertyIds.has(row.propertyId) && !caseIds.has(row.id));
  const workIds = new Set([...caseIds, ...work.map((row) => row.id)]);
  const pendingDrafts = snapshot.drafts.filter((draft) => draft.status === "pending" && propertyIds.has(draft.propertyId) && !workIds.has(draft.workItemId ?? `work-${draft.id}`));
  const rows = [
    ...cases.filter((row) => !FINISHED_STATES.has(row.state)).map((row) => `- Case ${cell(row.id)}: ${cell(row.kind)} for ${cell(row.propertyId)}; state ${cell(row.state)}. Open Desk for its detailed facts and decisions.`),
    ...work.filter((row) => !FINISHED_STATES.has(row.state)).map((row) => `- Work ${cell(row.id)}: ${cell(row.kind)} for ${cell(row.propertyId)}; state ${cell(row.state)}. Open Desk for its detailed facts and decisions.`),
    ...pendingDrafts.map((draft) => `- Prepared ${cell(draft.kind)} for ${cell(draft.propertyId)}; waiting for a person.`),
    ...snapshot.escalations.filter((row) => propertyIds.has(row.propertyId) && !caseIds.has(row.id)).map((row) => `- ${cell(row.propertyId)} needs licensed review (${cell(row.reason)}).`),
  ];
  lines.push(...(rows.length ? boundedRows(rows, rows.length, 24_000) : ["- No active property work is listed in this snapshot."]));

  lines.push("", "## Source boundary", "");
  lines.push(`- Last check: ${cell(snapshot.hands === "hermes" ? "Bud live" : snapshot.hands)}.`);
  lines.push("- Inbox data is not included in this snapshot. Unassigned cases and private case detail require review in Desk.");
  lines.push("- This projection never authorizes sending, paying, submitting, publishing, or issuing a notice.", "");
  const rendered = lines.join("\n");
  if (rendered.length > DESK_CONTEXT_MAX_CHARS) throw new Error("The Desk snapshot is too large to prepare safely. Narrow the property scope.");
  return rendered;
}

export function writeDeskContext(snapshot: DeskSnapshot, book?: string): string {
  const path = join(seedVault(book), DESK_CONTEXT_FILE);
  writeFileAtomic(path, deskContextMarkdown(snapshot), 0o600);
  return path;
}
