import { it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { isRemoteCommandEnrollment,isRemoteEnrollmentSnapshot,isRemoteEnrollmentConfirm,REMOTE_APPROVER_MS,type RemoteEnrollmentSnapshot } from '../shared/website-remote-approvers.ts';
import { isWebsiteCommandEnrollment } from '../shared/website-commands.ts';
function fixture(){const now=Date.now(),id=randomUUID(),grantId=randomUUID(),descriptor={id:randomUUID(),operation:'prepare-recipe' as const,revision:'a'.repeat(64),label:'Briefing'},scopes=[{descriptorId:descriptor.id,descriptorRevision:descriptor.revision,disclosureDigest:'b'.repeat(64)}];
 const person={subject:randomUUID(),identityEpoch:1,email:'person@example.test',agencyLabel:'Office',companyId:'company'};
 const snapshot:RemoteEnrollmentSnapshot={protocol:2,begin:{protocol:2,enrollmentId:id,grantId,generation:1,challengeHash:'c'.repeat(64),scopes,disclosurePolicy:'exact-reviewed-template-v1',expiresAt:new Date(now+600000).toISOString(),approverExpiresAt:new Date(now+REMOTE_APPROVER_MS).toISOString()},target:{workspaceLabel:'Workspace',descriptors:[descriptor]},candidate:person,phase:'confirmed',approver:{protocol:2,id,generation:1,parentGrantId:grantId,parentGeneration:1,installationId:randomUUID(),workspaceId:randomUUID(),workerBinding:randomUUID(),companyId:person.companyId,person,scopes,disclosurePolicy:'exact-reviewed-template-v1',enrolledAt:new Date(now).toISOString(),expiresAt:new Date(now+REMOTE_APPROVER_MS).toISOString(),revokedAt:null},serverTime:new Date(now).toISOString()};return snapshot;}
it('v2 parent cannot be admitted by legacy enrollment and rejects extra authority fields',()=>{const s=fixture(),g=s.approver!,v={protocol:2,grantId:g.parentGrantId,generation:1,installationId:g.installationId,workspaceId:g.workspaceId,workspaceLabel:s.target.workspaceLabel,workerBinding:g.workerBinding,descriptors:s.target.descriptors,commandToken:'a'.repeat(64)};expect(isRemoteCommandEnrollment(v)).toBe(true);expect(isWebsiteCommandEnrollment(v)).toBe(false);expect(isRemoteCommandEnrollment({...v,actor:'admin'})).toBe(false);});
it('snapshot links candidate, scope and grant exactly, independent of JSON key order',()=>{const s=fixture();expect(isRemoteEnrollmentSnapshot(s)).toBe(true);expect(isRemoteEnrollmentSnapshot({...s,candidate:Object.fromEntries(Object.entries(s.candidate!).reverse())})).toBe(true);
 for(const changed of [{...s,phase:['confirmed']},{...s,target:{...s.target,descriptors:[]}},{...s,candidate:{...s.candidate,identityEpoch:2}},{...s,approver:{...s.approver,revokedAt:s.serverTime}},{...s,serverTime:s.approver!.expiresAt},{...s,approver:{...s.approver,parentGeneration:2}}])expect(isRemoteEnrollmentSnapshot(changed)).toBe(false);
});
it('confirmation cannot substitute actor fields and dates cannot silently normalize',()=>{const s=fixture(),v={protocol:2,enrollmentId:s.begin.enrollmentId,grantId:s.begin.grantId,generation:1,candidate:s.candidate};expect(isRemoteEnrollmentConfirm(v)).toBe(true);expect(isRemoteEnrollmentConfirm({...v,providerSubject:randomUUID()})).toBe(false);expect(isRemoteEnrollmentSnapshot({...s,serverTime:'2026-02-31T00:00:00.000Z'})).toBe(false);});
