/** Versioned website request protocol. No source data, recipe ids, paths or instructions. */
export const WEBSITE_COMMAND_PROTOCOL = 1 as const;
export const COMMAND_PAGE_SIZE = 32;
export const COMMAND_OPERATIONS = ['morning-review', 'prepare-recipe'] as const;
export type WebsiteCommandOperation = typeof COMMAND_OPERATIONS[number];
export const COMMAND_PHASES = ['queued', 'delivered', 'accepted', 'running', 'completed', 'needs-review', 'partial', 'failed', 'interrupted', 'rejected', 'cancelled', 'expired', 'stale'] as const;
export type WebsiteCommandPhase = typeof COMMAND_PHASES[number];
export const COMMAND_OUTCOMES = ['prepared', 'review-required', 'partial-results', 'execution-failed', 'execution-interrupted', 'declined', 'cancelled', 'expired', 'binding-changed'] as const;
export type WebsiteCommandOutcome = typeof COMMAND_OUTCOMES[number];
export type WebsiteCommandDescriptor = { id: string; operation: WebsiteCommandOperation; revision: string; label: string };
export type WebsiteCommandEnrollment = { protocol: 1; grantId: string; generation: number; installationId: string; workspaceId: string; workspaceLabel: string; descriptors: WebsiteCommandDescriptor[]; commandToken: string };
export type WebsiteCommandGrant = Omit<WebsiteCommandEnrollment, 'commandToken'> & { companyId: string; enrolledAt: string; revokedAt: string | null };
export type WebsiteCommandEnvelope = { protocol: 1; id: string; companyId: string; installationId: string; workspaceId: string; grantId: string; generation: number; descriptor: WebsiteCommandDescriptor; requester: string; createdAt: string; expiresAt: string };
export type WebsiteCommandState = { envelope: WebsiteCommandEnvelope; revision: number; phase: WebsiteCommandPhase; cancellationRequested: boolean; runReference: string | null; outcome: WebsiteCommandOutcome | null; updatedAt: string; sequence: number };
export type WebsiteCommandPoll = { grantId: string; generation: number; cursor: number };
export type WebsiteCommandPollResult = { grant: WebsiteCommandGrant; requests: WebsiteCommandState[]; cursor: number; hasMore: boolean; serverTime: string };
export type WebsiteCommandEvent = { grantId: string; generation: number; requestId: string; eventId: string; expectedRevision: number; phase: WebsiteCommandPhase; outcome: WebsiteCommandOutcome | null; runReference: string | null };
export type WebsiteCommandClaim = { grantId: string; generation: number; requestId: string; expectedRevision: number; envelope: WebsiteCommandEnvelope; previewDigest: string; claimId: string };
export type WebsiteCommandClaimResult = { request: WebsiteCommandState; claimId: string; previewDigest: string; validUntil: string; serverTime: string };
export type WebsiteCommandSubmit = { requestId: string; grantId: string; descriptorId: string; descriptorRevision: string };
export type WebsiteCommandCatalog = { grant: WebsiteCommandGrant; installationLabel: string };
export type WebsiteCommandTargetReference = { grantId: string; installationId: string; workspaceId: string; installationLabel: string; workspaceLabel: string };
export type WebsiteCommandAccountResult = { targetReferences: WebsiteCommandTargetReference[]; catalog: WebsiteCommandCatalog[]; requests: WebsiteCommandState[]; cursor: number; hasMore: boolean; serverTime: string };
export const commandUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export const commandDigest = /^[a-f0-9]{64}$/;
const obj = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);
const exact = (v: unknown, keys: string[]): v is Record<string, unknown> => obj(v) && Object.keys(v).length === keys.length && keys.every(k => Object.hasOwn(v, k));
export const commandLabel = (v: unknown, max = 80): v is string => typeof v === 'string' && v.length > 0 && v.length <= max && v.trim() === v && !/[\u0000-\u001f\u007f]/.test(v);
const uuid = (v: unknown): v is string => typeof v === 'string' && commandUuid.test(v);
const digest = (v: unknown): v is string => typeof v === 'string' && commandDigest.test(v);
const positive = (v: unknown): v is number => Number.isSafeInteger(v) && (v as number) > 0 && (v as number) <= 2147483647;
const cursor = (v: unknown): v is number => Number.isSafeInteger(v) && (v as number) >= 0;
const date = (v: unknown): v is string => typeof v === 'string' && /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v) && Number.isFinite(Date.parse(v));
export function isWebsiteCommandDescriptor(v: unknown): v is WebsiteCommandDescriptor { return exact(v, ['id','operation','revision','label']) && uuid(v.id) && COMMAND_OPERATIONS.includes(v.operation as WebsiteCommandOperation) && digest(v.revision) && commandLabel(v.label); }
const enrollmentKeys = ['protocol','grantId','generation','installationId','workspaceId','workspaceLabel','descriptors'];
function grantFields(v: Record<string, unknown>): boolean { return v.protocol === 1 && uuid(v.grantId) && positive(v.generation) && uuid(v.installationId) && uuid(v.workspaceId) && commandLabel(v.workspaceLabel) && Array.isArray(v.descriptors) && v.descriptors.length > 0 && v.descriptors.length <= 16 && v.descriptors.every(isWebsiteCommandDescriptor) && new Set(v.descriptors.map(d => d.id)).size === v.descriptors.length; }
export function isWebsiteCommandEnrollment(v: unknown): v is WebsiteCommandEnrollment { return exact(v, [...enrollmentKeys,'commandToken']) && grantFields(v) && digest(v.commandToken); }
export function isWebsiteCommandGrant(v: unknown): v is WebsiteCommandGrant { return exact(v, [...enrollmentKeys,'companyId','enrolledAt','revokedAt']) && grantFields(v) && commandLabel(v.companyId,100) && date(v.enrolledAt) && (v.revokedAt === null || date(v.revokedAt)); }
export function isWebsiteCommandEnvelope(v: unknown): v is WebsiteCommandEnvelope { return exact(v, ['protocol','id','companyId','installationId','workspaceId','grantId','generation','descriptor','requester','createdAt','expiresAt']) && v.protocol === 1 && uuid(v.id) && commandLabel(v.companyId,100) && uuid(v.installationId) && uuid(v.workspaceId) && uuid(v.grantId) && positive(v.generation) && isWebsiteCommandDescriptor(v.descriptor) && commandLabel(v.requester,160) && date(v.createdAt) && date(v.expiresAt) && Date.parse(v.expiresAt) > Date.parse(v.createdAt) && Date.parse(v.expiresAt)-Date.parse(v.createdAt) <= 86400000; }
export function isWebsiteCommandState(v: unknown): v is WebsiteCommandState { return exact(v, ['envelope','revision','phase','cancellationRequested','runReference','outcome','updatedAt','sequence']) && isWebsiteCommandEnvelope(v.envelope) && positive(v.revision) && COMMAND_PHASES.includes(v.phase as WebsiteCommandPhase) && typeof v.cancellationRequested === 'boolean' && (v.runReference === null || uuid(v.runReference)) && (v.outcome === null || COMMAND_OUTCOMES.includes(v.outcome as WebsiteCommandOutcome)) && date(v.updatedAt) && cursor(v.sequence); }
export function isWebsiteCommandPoll(v: unknown): v is WebsiteCommandPoll { return exact(v, ['grantId','generation','cursor']) && uuid(v.grantId) && positive(v.generation) && cursor(v.cursor); }
export function isWebsiteCommandSubmit(v: unknown): v is WebsiteCommandSubmit { return exact(v, ['requestId','grantId','descriptorId','descriptorRevision']) && uuid(v.requestId) && uuid(v.grantId) && uuid(v.descriptorId) && digest(v.descriptorRevision); }
export function isWebsiteCommandEvent(v: unknown): v is WebsiteCommandEvent { return exact(v, ['grantId','generation','requestId','eventId','expectedRevision','phase','outcome','runReference']) && uuid(v.grantId) && positive(v.generation) && uuid(v.requestId) && uuid(v.eventId) && positive(v.expectedRevision) && COMMAND_PHASES.includes(v.phase as WebsiteCommandPhase) && (v.outcome === null || COMMAND_OUTCOMES.includes(v.outcome as WebsiteCommandOutcome)) && (v.runReference === null || uuid(v.runReference)); }
export function isWebsiteCommandClaim(v: unknown): v is WebsiteCommandClaim { return exact(v, ['grantId','generation','requestId','expectedRevision','envelope','previewDigest','claimId']) && uuid(v.grantId) && positive(v.generation) && uuid(v.requestId) && positive(v.expectedRevision) && isWebsiteCommandEnvelope(v.envelope) && v.envelope.id === v.requestId && v.envelope.grantId === v.grantId && v.envelope.generation === v.generation && digest(v.previewDigest) && uuid(v.claimId); }
export function isWebsiteCommandPollResult(v: unknown): v is WebsiteCommandPollResult { return exact(v,['grant','requests','cursor','hasMore','serverTime']) && isWebsiteCommandGrant(v.grant) && Array.isArray(v.requests) && v.requests.length <= COMMAND_PAGE_SIZE && v.requests.every(isWebsiteCommandState) && cursor(v.cursor) && typeof v.hasMore === 'boolean' && date(v.serverTime); }
export function isWebsiteCommandClaimResult(v: unknown): v is WebsiteCommandClaimResult { return exact(v,['request','claimId','previewDigest','validUntil','serverTime']) && isWebsiteCommandState(v.request) && uuid(v.claimId) && digest(v.previewDigest) && date(v.validUntil) && date(v.serverTime); }
/** Deterministic digest input across object key order, not a SQL hash contract. */
export function canonicalWebsiteCommand(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonicalWebsiteCommand).join(',')}]`; if (obj(value)) return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonicalWebsiteCommand(value[k])}`).join(',')}}`; const text=JSON.stringify(value); if(text === undefined) throw new Error('Invalid command value'); return text; }

export function isWebsiteCommandAccountResult(v: unknown): v is WebsiteCommandAccountResult { return exact(v,['catalog','targetReferences','requests','cursor','hasMore','serverTime']) && Array.isArray(v.targetReferences) && v.targetReferences.length <= COMMAND_PAGE_SIZE && v.targetReferences.every(t => exact(t,['grantId','installationId','workspaceId','installationLabel','workspaceLabel']) && uuid(t.grantId) && uuid(t.installationId) && uuid(t.workspaceId) && commandLabel(t.installationLabel) && commandLabel(t.workspaceLabel)) && new Set(v.targetReferences.map(t=>t.grantId)).size === v.targetReferences.length && Array.isArray(v.catalog) && v.catalog.length <= 1000 && v.catalog.every(c => exact(c,['grant','installationLabel']) && isWebsiteCommandGrant(c.grant) && commandLabel(c.installationLabel)) && Array.isArray(v.requests) && v.requests.length <= COMMAND_PAGE_SIZE && v.requests.every(isWebsiteCommandState) && cursor(v.cursor) && typeof v.hasMore === 'boolean' && date(v.serverTime); }
